
Testing libretokindlehtml.test.core

ERROR in (test-list-of-resources) (AFn.java:437)
expected: (= (pr-str result) correct-str)
  actual: clojure.lang.ArityException: Wrong number of args (1) passed to: core$list-of-resources$fn
 at clojure.lang.AFn.throwArity (AFn.java:437)
    clojure.lang.AFn.invoke (AFn.java:39)
    clojure.core$map$fn__3811.invoke (core.clj:2432)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:60)
    clojure.lang.RT.seq (RT.java:466)
    clojure.core$seq.invoke (core.clj:133)
    clojure.core$map$fn__3811.invoke (core.clj:2424)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:60)
    clojure.lang.RT.seq (RT.java:466)
    clojure.core$seq.invoke (core.clj:133)
    clojure.core$print_sequential.invoke (core_print.clj:46)
    clojure.core/fn (core_print.clj:140)
    clojure.lang.MultiFn.invoke (MultiFn.java:167)
    clojure.core$pr_on.invoke (core.clj:3264)
    clojure.core$pr.invoke (core.clj:3276)
    clojure.lang.AFn.applyToHelper (AFn.java:161)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.core$apply.invoke (core.clj:600)
    clojure.core$pr_str.doInvoke (core.clj:4193)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    libretokindlehtml.test.core$fn__278$fn__279.invoke (core.clj:32)
    libretokindlehtml.test.core/fn (core.clj:32)
    clojure.test$test_var$fn__6484.invoke (test.clj:693)
    clojure.test$test_var.invoke (test.clj:693)
    clojure.test$test_all_vars$fn__6488$fn__6495.invoke (test.clj:709)
    clojure.test$default_fixture.invoke (test.clj:663)
    clojure.test$test_all_vars$fn__6488.invoke (test.clj:709)
    clojure.test$default_fixture.invoke (test.clj:663)
    clojure.test$test_all_vars.invoke (test.clj:705)
    clojure.test$test_ns.invoke (test.clj:728)
    clojure.core$map$fn__3811.invoke (core.clj:2432)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:60)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.boundedLength (RT.java:1607)
    clojure.lang.RestFn.applyTo (RestFn.java:130)
    clojure.core$apply.invoke (core.clj:602)
    clojure.test$run_tests.doInvoke (test.clj:743)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:600)
    user$eval29$fn__41.invoke (NO_SOURCE_FILE:1)
    user$eval29.invoke (NO_SOURCE_FILE:1)
    clojure.lang.Compiler.eval (Compiler.java:6465)
    clojure.lang.Compiler.eval (Compiler.java:6455)
    clojure.lang.Compiler.eval (Compiler.java:6431)
    clojure.core$eval.invoke (core.clj:2795)
    clojure.main$eval_opt.invoke (main.clj:296)
    clojure.main$initialize.invoke (main.clj:315)
    clojure.main$null_opt.invoke (main.clj:348)
    clojure.main$main.doInvoke (main.clj:426)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:405)
    clojure.lang.AFn.applyToHelper (AFn.java:163)
    clojure.lang.Var.applyTo (Var.java:518)
    clojure.main.main (main.java:37)

FAIL in (test-order-map) (core.clj:25)
expected: (= (order-map :order ["pro" "c1" "c2" "c3" "after"]) {"pro" 0, "c1" 1, "c2" 2, "c3" 3, "after" 4})
  actual: (not (= ["pro" "c1" "c2" "c3" "after"] {"pro" 0, "c1" 1, "c2" 2, "c3" 3, "after" 4}))

Ran 2 tests containing 5 assertions.
1 failures, 1 errors.
